GalleySearch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("applicant/", include("applicant.urls")),
    path("employer/", include("employer.urls")),
    path("search/", include("search.urls")),
    path("", include("account.urls")),
]

applicant/urls.py
from django.urls import path

from applicant.views import (
    ResumeListView,
    ResumeDetailView,
    ResumeCreateView,
    ResumeUpdateView,
    ResumeDeleteView,
    MyResumesListView,
)

app_name = "applicant"

urlpatterns = [
    path("resumes/", ResumeListView.as_view(), name="resumes"),
    path("resume/<int:pk>/", ResumeDetailView.as_view(), name="resume-detail"),
    path("resume/create-resume/", ResumeCreateView.as_view(), name="create-resume"),
    path("resume/<int:pk>/edit/", ResumeUpdateView.as_view(), name="edit-resume"),
    path("resume/<int:pk>/delete/", ResumeDeleteView.as_view(), name="delete-resume"),
    path("my-resumes/", MyResumesListView.as_view(), name="my-resumes"),
]

search/urls.py
from django.urls import path
from .views import SearchResultListView

app_name = "search"

urlpatterns = [
    path("", SearchResultListView.as_view(), name="search"),
]

applicant/models.py
from django.db import models
from django.urls import reverse
from djmoney.models.fields import MoneyField

from account.models import Applicant


class Resume(models.Model):
    GENDER_CHOICE = (("M", "Male"), ("F", "Female"))
    applicant = models.ForeignKey(
        Applicant, on_delete=models.CASCADE, related_name="applicant"
    )
    first_name = models.CharField(max_length=50, verbose_name="Имя")
    last_name = models.CharField(max_length=50, verbose_name="Фамилия")
    birthday = models.DateField(verbose_name="Дата рождения")
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE, verbose_name="Пол")
    position = models.CharField(
        max_length=100, verbose_name="Желаемая должность", db_index=True
    )
    city = models.CharField(max_length=100, verbose_name="Город")
    email = models.EmailField(verbose_name="Почта для связи")
    salary_to = MoneyField(
        max_digits=14,
        decimal_places=2,
        default_currency="RUB",
        verbose_name="Заработная плата",
    )
    is_published = models.BooleanField(verbose_name="Опубликовать", default=True)

    class Meta:
        verbose_name = "Резюме"
        verbose_name_plural = "Резюме"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("applicant:resume-detail", kwargs={"pk": self.pk})

    def pretty_money(self):
        return f"{self.salary_to.amount} {self.salary_to_currency}"

applicant/forms.py
from django import forms
from djmoney.forms import MoneyField, MoneyWidget

from applicant.models import Resume


class CreateResumeForm(forms.ModelForm):
    gender = forms.ChoiceField(
        choices=Resume.GENDER_CHOICE,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    salary_to = MoneyField(
        default_currency="RUB",
        widget=MoneyWidget(
            amount_widget=forms.TextInput(
                attrs={"class": "form-control-mg3", "placeholder": "Salary"}
            )
        ),
    )
    is_published = forms.RadioSelect()

    class Meta:
        model = Resume
        fields = (
            "first_name",
            "last_name",
            "birthday",
            "gender",
            "position",
            "city",
            "email",
            "salary_to",
            "is_published",
        )

        widgets = {
            "first_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "First name"}
            ),
            "last_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Last name"}
            ),
            "birthday": forms.DateInput(
                attrs={"class": "form-control", "placeholder": "YYYY-MM-DD"}
            ),
            "position": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Position"}
            ),
            "city": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "City"}
            ),
            "email": forms.EmailInput(
                attrs={"class": "form-control", "placeholder": "Email"}
            ),
        }

applicant/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)

from applicant.forms import CreateResumeForm
from applicant.mixins import ApplicantLoginRequiredMixin
from applicant.models import Resume


class ResumeListView(ApplicantLoginRequiredMixin, ListView):
    model = Resume
    template_name = "applicant/resumes.html"
    context_object_name = "resumes"

    queryset = Resume.objects.filter(is_published=True)


class MyResumesListView(ResumeListView):
    def get_queryset(self):
        return super().get_queryset().filter(applicant=self.request.user)


class ResumeDetailView(ApplicantLoginRequiredMixin, DetailView):
    model = Resume
    template_name = "applicant/resume-detail.html"


class ResumeCreateView(ApplicantLoginRequiredMixin, CreateView):
    model = Resume
    form_class = CreateResumeForm
    template_name = "applicant/resume-create.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["initial"] = {"email": self.request.user.email}
        return kwargs

    def form_valid(self, form):
        form.instance.applicant = self.request.user
        return super().form_valid(form)


class ResumeUpdateView(ApplicantLoginRequiredMixin, UpdateView):
    model = Resume
    form_class = CreateResumeForm
    template_name = "applicant/resume-edit.html"


class ResumeDeleteView(ApplicantLoginRequiredMixin, DeleteView):
    model = Resume
    success_url = reverse_lazy("applicant:resumes")
    template_name = "applicant/resume_confirm_delete.html"

applicant/templates/applicant/resume-create.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <form method="post">

        {% csrf_token %}
        {{ form.as_p }}
        <div class="col text-center">
            <button type="submit" class="btn btn-primary  mb-4">Создать резюме</button>
        </div>
    </form>
</div>

{% endblock %}

applicant/templates/applicant/resume-detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container" style="max-width:800px">
        <div class="centered">
            <ul class="list-group">
              <li class="list-group-item">{{ resume.position }}</li>
              <li class="list-group-item">{{ resume.first_name }}</li>
              <li class="list-group-item">{{ resume.last_name }}</li>
              <li class="list-group-item">{{ resume.birthday }}</li>
              <li class="list-group-item">{{ resume.get_gender_display }}</li>
              <li class="list-group-item">{{ resume.city }}</li>
              <li class="list-group-item">{{ resume.email }}</li>
              <li class="list-group-item">{{ resume.pretty_money }}</li>
              <li class="list-group-item">{{ resume.is_published }}</li>
            </ul>
            <div class="col text-center">
                <a href='{% url 'applicant:edit-resume' pk=resume.pk %}'>Изменить</a>
            </div>
        </div>
    </div>
{% endblock %}

applicant/templates/applicant/resume-edit.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <ul>
                {{ form.as_p }}
            </ul>
            <div class="col text-center">
                <div>
                    <button formmethod="post" type="submit">Сохранить изменения</button>
                </div>
                <div>
                    <a href="{% url "applicant:delete-resume" pk=resume.pk%}" rel="nofollow">Удалить резюме</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

applicant/templates/applicant/resume_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    <div class="container col text-center">
        <p>Вы уверены что хотите удалить резюме "{{ resume.position }}"?</p>
        <input type="submit" value="Удалить">
    </div>
    </form>
{% endblock %}

applicant/templates/applicant/resumes.html
{% extends "base.html" %}

{% block content %}
    {% for resume in resumes %}
        <div class="container">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="{% url 'applicant:resume-detail' pk=resume.pk %}">{{ resume.position }}</a>
            </li>
            <li class="list-group-item">{{ resume }}</li>
            <li class="list-group-item">{{ resume.pretty_money }}</li>
        </ul>
        </div>
        <hr/>
    {% endfor %}
{% endblock %}