GalleySearch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("applicant/", include("applicant.urls")),
    path("employer/", include("employer.urls")),
    path("search/", include("search.urls")),
    path("", include("account.urls")),
]

employer/urls.py
from django.urls import path
from employer.views import (
    VacancyListView,
    VacancyDetailView,
    VacancyCreateView,
    VacancyUpdateView,
    VacancyDeleteView,
    MyVacancyListView,
)

app_name = "employer"

urlpatterns = [
    path("vacancies/", VacancyListView.as_view(), name="vacancies"),
    path("vacancy/<int:pk>/", VacancyDetailView.as_view(), name="vacancy-detail"),
    path("vacancy/create-vacancy", VacancyCreateView.as_view(), name="vacancy-create"),
    path("vacancy/<int:pk>/edit", VacancyUpdateView.as_view(), name="vacancy-edit"),
    path("vacancy/<int:pk>/delete", VacancyDeleteView.as_view(), name="vacancy-delete"),
    path("my-vacancies/", MyVacancyListView.as_view(), name="my-vacancies"),
]

search/urls.py
from django.urls import path
from .views import SearchResultListView

app_name = "search"

urlpatterns = [
    path("", SearchResultListView.as_view(), name="search"),
]

employer/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from djmoney.models.fields import MoneyField
from django.urls import reverse
from account.models import EmployerManager, User, Employer


class Vacancy(models.Model):
    EXPERIENCE_CHOICE = (
        ("WE", "Без опыта"),
        ("1+", "От 1 года"),
        ("2+", "От 2 лет"),
        ("3+", "От 3 лет"),
        ("5+", "Больше 5 лет"),
    )

    EMPLOYMENT_TYPE_CHOICE = (
        ("FT", "Полная занятость"),
        ("PT", "Частичная занятость"),
        ("IN", "Стажировка"),
        ("PW", "Проектная работа"),
    )

    employer = models.ForeignKey(
        Employer, on_delete=models.CASCADE, related_name="employer"
    )
    position = models.CharField(max_length=100, verbose_name="Должность")
    experience = models.CharField(
        max_length=2,
        verbose_name="Опыт работы",
        default="WE",
        choices=EXPERIENCE_CHOICE,
    )
    city = models.CharField(max_length=100, verbose_name="Город")
    salary_to = MoneyField(
        max_digits=14,
        decimal_places=2,
        default_currency="RUB",
        verbose_name="Зарплата до",
        blank=True,
    )
    salary_from = MoneyField(
        max_digits=14,
        decimal_places=2,
        default_currency="RUB",
        verbose_name="Зарплата от",
        blank=True,
    )
    employment_type = models.CharField(
        max_length=2,
        verbose_name="Тип занятости",
        default="FT",
        choices=EMPLOYMENT_TYPE_CHOICE,
    )
    is_published = models.BooleanField(verbose_name="Опубликовать", default=True)

    class Meta:
        verbose_name = "Вакансия"
        verbose_name_plural = "Вакансии"

    def __str__(self):
        return self.position

    def get_absolute_url(self):
        return reverse("employer:vacancy-detail", kwargs={"pk": self.pk})

    def pretty_money(self):
        if self.salary_to and self.salary_from:
            return f"От {self.salary_from.amount} до {self.salary_to.amount} {self.salary_to_currency}"
        elif self.salary_to:
            return f"До {self.salary_to.amount} {self.salary_to_currency}"
        elif self.salary_from:
            f"От {self.salary_from.amount} {self.salary_from_currency}"
        return "Не указано"

employer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from employer.models import Vacancy


class VacancyCreateForm(forms.ModelForm):
    experience = forms.ChoiceField(
        choices=Vacancy.EXPERIENCE_CHOICE,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    employment_type = forms.ChoiceField(
        choices=Vacancy.EMPLOYMENT_TYPE_CHOICE,
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    is_published = forms.RadioSelect()

    class Meta:
        model = Vacancy
        fields = (
            "position",
            "experience",
            "city",
            "salary_from",
            "salary_to",
            "employment_type",
            "is_published",
        )

        widgets = {
            "position": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Position"}
            ),
            "city": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "City"}
            ),
        }

employer/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    CreateView,
    DeleteView,
)

from employer.mixins import EmployerLoginRequiredMixin
from employer.models import Vacancy
from employer.forms import (
    VacancyCreateForm,
)


class VacancyListView(EmployerLoginRequiredMixin, ListView):
    models = Vacancy
    template_name = "employer/vacancies.html"
    context_object_name = "vacancies"

    queryset = Vacancy.objects.filter(is_published=True)


class MyVacancyListView(VacancyListView):
    def get_queryset(self):
        return super().get_queryset().filter(employer=self.request.user)


class VacancyDetailView(EmployerLoginRequiredMixin, DetailView):
    model = Vacancy
    template_name = "employer/vacancy-detail.html"


class VacancyUpdateView(EmployerLoginRequiredMixin, UpdateView):
    model = Vacancy
    form_class = VacancyCreateForm
    template_name = "employer/vacancy-edit.html"


class VacancyCreateView(EmployerLoginRequiredMixin, CreateView):
    model = Vacancy
    form_class = VacancyCreateForm
    template_name = "employer/vacancy-create.html"

    def form_valid(self, form):
        form.instance.employer = self.request.user
        return super(VacancyCreateView, self).form_valid(form)


class VacancyDeleteView(EmployerLoginRequiredMixin, DeleteView):
    model = Vacancy
    success_url = reverse_lazy("employer:vacancies")
    template_name = "employer/vacancy_confirm_delete.html"

employer/templates/employer/vacancies.html
{% extends "base.html" %}

{% block content %}
    {% for vacancy in vacancies %}
        <div class="container">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="{% url 'employer:vacancy-detail' pk=vacancy.pk %}">{{ vacancy.position }}</a>
            </li>
            <li class="list-group-item">{{ vacancy }}</li>
            <li class="list-group-item">{{ vacancy.pretty_money }}</li>
            <li class="list-group-item">{{ vacancy.employer.employerprofile.company_name }}</li>
        </ul>
        </div>
        <hr/>
    {% endfor %}
{% endblock %}

employer/templates/employer/vacancy-create.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <form method="post">

        {% csrf_token %}
        {{ form.as_p }}
        <div class="col text-center">
            <button type="submit" class="btn btn-primary  mb-4">Создать вакансию</button>
        </div>
    </form>
</div>

{% endblock %}

employer/templates/employer/vacancy-detail.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="max-width:800px">
    <div class="centered">
        <ul class="list-group">
          <li class="list-group-item">{{ vacancy.position }}</li>
          <li class="list-group-item">{{ vacancy.experience }}</li>
          <li class="list-group-item">{{ vacancy.city }}</li>
          <li class="list-group-item">{{ vacancy.employment_type }}</li>
          <li class="list-group-item">{{ vacancy.pretty_money }}</li>
          <li class="list-group-item">{{ vacancy.is_published }}</li>
          <li class="list-group-item">{{ vacancy.employer.employerprofile.company_name }}</li>
        </ul>
        <div class="col text-center">
        <a href='{% url 'employer:vacancy-edit' pk=vacancy.pk %}'>Изменить</a>
        </div>
    </div>
</div>
{% endblock %}

employer/templates/employer/vacancy-edit.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <ul>
            {{ form.as_p }}
        </ul>
        <div class="col text-center">
            <button formmethod="post" type="submit">Сохранить изменения</button>

            <a href="{% url "employer:vacancy-delete" pk=vacancy.pk %}" rel="nofollow">Удалить вакансию</a>
        </div>
    </form>
</div>
{% endblock %}

employer/templates/employer/vacancy_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    <div class="container col text-center">
        <p>Вы уверены что хотите удалить вакансию "{{ vacancy.position }}"?</p>
        <input type="submit" value="Удалить">
    </div>
    </form>
{% endblock %}