GalleySearch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("applicant/", include("applicant.urls")),
    path("employer/", include("employer.urls")),
    path("search/", include("search.urls")),
    path("", include("account.urls")),
]

account/urls.py
from django.urls import path

from account.views import (
    employer_register_view,
    employer_register_company_view,
    UserLoginView,
    main_page_view,
    logout_view,
    applicant_register_view,
    ProfileView,
    profile_edit_view,
)

app_name = "account"

urlpatterns = [
    path("", main_page_view, name="main-page"),
    path("register-employer/", employer_register_view, name="employer-register"),
    path(
        "register-company/",
        employer_register_company_view,
        name="employer-register-company",
    ),
    path("register-applicant/", applicant_register_view, name="applicant-register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("accounts/profile/", ProfileView.as_view(), name="self-profile"),
    path("accounts/profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("accounts/profile/edit/", profile_edit_view, name="profile-edit"),
]

applicant/urls.py
from django.urls import path

from applicant.views import (
    ResumeListView,
    ResumeDetailView,
    ResumeCreateView,
    ResumeUpdateView,
    ResumeDeleteView,
    MyResumesListView,
)

app_name = "applicant"

urlpatterns = [
    path("resumes/", ResumeListView.as_view(), name="resumes"),
    path("resume/<int:pk>/", ResumeDetailView.as_view(), name="resume-detail"),
    path("resume/create-resume/", ResumeCreateView.as_view(), name="create-resume"),
    path("resume/<int:pk>/edit/", ResumeUpdateView.as_view(), name="edit-resume"),
    path("resume/<int:pk>/delete/", ResumeDeleteView.as_view(), name="delete-resume"),
    path("my-resumes/", MyResumesListView.as_view(), name="my-resumes"),
]

employer/urls.py
from django.urls import path
from employer.views import (
    VacancyListView,
    VacancyDetailView,
    VacancyCreateView,
    VacancyUpdateView,
    VacancyDeleteView,
    MyVacancyListView,
)

app_name = "employer"

urlpatterns = [
    path("vacancies/", VacancyListView.as_view(), name="vacancies"),
    path("vacancy/<int:pk>/", VacancyDetailView.as_view(), name="vacancy-detail"),
    path("vacancy/create-vacancy", VacancyCreateView.as_view(), name="vacancy-create"),
    path("vacancy/<int:pk>/edit", VacancyUpdateView.as_view(), name="vacancy-edit"),
    path("vacancy/<int:pk>/delete", VacancyDeleteView.as_view(), name="vacancy-delete"),
    path("my-vacancies/", MyVacancyListView.as_view(), name="my-vacancies"),
]

search/urls.py
from django.urls import path
from .views import SearchResultListView

app_name = "search"

urlpatterns = [
    path("", SearchResultListView.as_view(), name="search"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/64060e7193.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %} Welcome to Galley Search {% endblock %}</title>
</head>
<header style="background-color: #f1f1f1;">
    {% include 'header.html' %}
</header>

<body>
    {% block content %}
    {% endblock %}
</body>

<footer class="text-center text-white" style="background-color: #f1f1f1;">
{% include 'footer.html' %}
</footer>

</html>

templates/footer.html
 <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->

    <section class="mb-4">

      <!-- VK -->
      <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://vk.com/GGnya"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="fa-brands fa-vk"></i></a>

      <!-- Gitlab -->
      <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://gitlab.com/GGnya"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="fa-brands fa-gitlab"></i></a>

      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="https://github.com/GGnya"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fa-brands fa-github"></i></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright:
    <a class="text-dark" href="https://hh.ru/resume/9ae4de5eff0bb27a6d0039ed1f695777665a57">GGnya</a>
  </div>
  <!-- Copyright -->

templates/header.html
{% load static %}


<header class="p-3 mb-3 border-bottom">
   <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center">
         <div>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                            <li><a href="{% url 'account:main-page' %}"><img width="40" src={% static "images/gs_logo.png" %} alt="logo"/></a></li>
                        {% if request.user.is_authenticated %}
                            {% if request.user.role == 'APPLICANT' %}
                                <li><a href="{% url 'employer:vacancies' %}" class="nav-link px-2 link-secondary">Vacancies</a></li>
                                <li><a href="{% url 'applicant:create-resume' %}" class="nav-link px-2 link-dark">Create resume</a></li>
                                <li><a href="{% url 'applicant:my-resumes' %}" class="nav-link px-2 link-dark">My resumes</a></li>
                            {% elif request.user.role == 'EMPLOYER' %}
                                <li><a href="{% url 'applicant:resumes' %}" class="nav-link px-2 link-secondary">Resumes</a></li>
                                <li><a href="{% url 'employer:vacancy-create' %}" class="nav-link px-2 link-dark">Vacancy create</a></li>
                                <li><a href="{% url 'employer:my-vacancies' %}" class="nav-link px-2 link-dark">My vacancies</a></li>
                            {% endif %}
                                <li><a href="{% url 'account:self-profile' %}" class="nav-link px-2 link-dark">Profile</a></li>
                                <li><a href="{% url 'search:search' %}" class="nav-link px-2 link-dark">Search</a> </li>
                                <li><a href="{% url 'account:logout' %}" class="nav-link px-2 link-dark">Log out</a> </li>
                        {% endif %}
            </ul>
         </div>
      </div>
   </div>
</header>